### ISSUE TITLE
Split Uncategorized.sublime-completions by library

### ISSUE THREAD

**Issue by p4t5h3** [SublimeLinter/SublimeLinter-template#6]
This eases maintenance and navigation.

**Comment by kaste** [comment]
I think you're in the wrong repo.  😉

**Comment by p4t5h3** [comment]
Yes, you are right. This was an accident. 😅 I was having a look on how to write a plugin and apparently clicked the "New issue" button in the wrong browser tab while working on [a syntax definition](https://github.com/peterthomashorn/purebasic-language-for-sublime-text).
